### ISSUE TITLE
Unknown command 'fzf'

### ISSUE THREAD

**Issue by mesqueeb** [decors/fish-ghq#6]
I have this error
```
~> fish: Unknown command 'fzf'
- (line 1):
begin; fzf
       ^
from sourcing file -
	called on line 61 of file /usr/local/Cellar/fish/3.0.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 12 of file ~/.config/fish/functions/__ghq_crtl_g.fish

in function '__ghq_crtl_g'
	called on standard input
```
i installed with `fisher decors/fish-ghq`

**Comment by mesqueeb** [comment]
solved by
1. `brew install fzf`
2. `fisher update` (or self-update, anyway it wasn't latest version)
3. `fisher add decors/fish-ghq`

**Comment by decors** [comment]
I added installation details 👍 

442e176422e8f3c1f0e1d821ee28fd057e8b3589

**Comment by jdempcy** [comment]
Step 3 is `fisher install decors/fish-ghq`

Thanks! This worked for me!
