### ISSUE TITLE
GHQ shortcut is always reset after new terminal window (日本語ok)

### ISSUE THREAD

**Issue by mesqueeb** [decors/fish-ghq#7]
（日本語下）
Hi.
I'm using iTerm 2 terminal and fish & fisher.
I did a global install of `fzf` with `brew install fzf`.

👍🏻 If I do: `fisher add decors/fish-ghq`
then ⌘+G works and points to my `.ghq` folder in my User folder.

👎🏻 If I close the terminal window and open it again, or if I open a new tab:
then ⌘+G starts generating a giant list with folders starting with `Music`...
<img width="464" alt="image" src="https://user-images.githubusercontent.com/3253920/52907186-50e6c280-329f-11e9-9f2d-a1d9dbec1a1d.png">

This means:
**Every time I want to use ⌘+G for the ghq list, I need to reinstall fish-ghq by doing `fisher add decors/fish-ghq`**... Then it works again, until I close the terminal window.

Any ideas for me?

**Comment by mesqueeb** [comment]
オーサーが日本語の方が強いと思い、日本語でも説明します。

👍🏻　`fisher add decors/fish-ghq`をiTerm 2で実行すれば、
GHQのrepo一覧が`⌘+G`で普通に出てきます。

👎🏻　ただし、一度terminal windowを閉じれば、`⌘+G`が壊れてしまう。
新しいwindowで再度`⌘+G`を押すと、なぜか `Music`フォルダから初め、長いフォルダ一覧が出てきます。

要するに、terminalを開くたび、`fisher add decors/fish-ghq`を再実行しない限り、このプラグイン使えません。

なにかセットアップでも間違えたのかなかと思います、、、、、
なにかアドバイスあれば大変助かります！！

**Comment by mesqueeb** [comment]
It worked when I did:
- `touch ~/.config/fish/functions/fish_user_key_bindings.fish`
and paste this inside:
```
### ghq ###
    bind \cg '__ghq_repository_search'
    if bind -M insert >/dev/null ^/dev/null
        bind -M insert \cg '__ghq_repository_search'
    end
    ### ghq ###
```

EDIT:
- updated the function name `__ghq_crtl_g` to `__ghq_repository_search` in the answer above.

It seems the author had renamed the function:
https://github.com/decors/fish-ghq/commit/6b7d820c19b1d9f85fb2f4272ca93e87ca12e9f6#diff-88d8c7864bce76000521ece291496116

**Comment by mesqueeb** [comment]
@decors キーボード・ショートカットを自分で `fish_user_key_bindings.fish` で設定しないといけないのが普通のやり方ですか？

なぜか、わたしの場合 `fisher add decors/fish-ghq` をインストールするだけだと、iTermを再起動したら、ctrl + G のショートカットが使えなくなる・・・・

でも上記の投稿のように、自分で `fish_user_key_bindings.fish` を設定すれば、ずっといける。

わたしの環境では何かだめな何かあるのかな・・・

**Comment by decors** [comment]
@mesqueeb 日本語でありがとうございます
[jethrokuan/fzf](https://github.com/jethrokuan/fzf) をインストールされていますでしょうか？

その場合、jethrokuan/fzf でも crtl-G のキーバインディングが追加されたため、コンフリクトします
`set -U FZF_LEGACY_KEYBINDINGS 0`
で jethrokuan/fzf の新しいキーバインディングに変更すると、利用できるかと思います
